spring:
  security:
    oauth2:
      client:
        registration:
          yandex:
            redirect-uri: "${OAUTH2_REDIRECT_URI:http://72.56.14.213/login/oauth2/code/yandex}"

  datasource:
    url: jdbc:postgresql://user-db:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: false

logging:
  level:
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.springframework.web.reactive: WARN

user:
  service:
    url: http://user-service:8081
    verify: http://user-service:8081/v1/users/

notification:
  service:
    url: http://notification-service:8082

app:
  frontend-url: ${APP_BASE_URL:http://72.56.14.213}
