spring:
  datasource:
    url: jdbc:postgresql://notification-db:5432/${NOTIFICATION_DB_NAME}
    username: ${NOTIFICATION_DB_USER}
    password: ${NOTIFICATION_DB_PASSWORD}

  jpa:
    show-sql: false

  kafka:
    bootstrap-servers: kafka:29092

app:
  user-service:
    url: http://user-service:8081

  frontend-url: ${FRONTEND_URL:http://rfsnab.ru}

  email:
    verification-url: ${APP_BASE_URL:https://rfsnab.ru}/verify-email
    legal-entity-confirm-url: ${APP_BASE_URL:https://rfsnab.ru}/api/v1/legal-entities/confirm-email
    legal-entity-link-confirm-url: ${APP_BASE_URL:https://rfsnab.ru}/api/v1/legal-entities/confirm-link

logging:
  level:
    ru.rfsnab.notificationservice: INFO
    org.springframework.kafka: WARN
    org.springframework.mail: WARN
