import type { OrderStatus } from '@/types/order';

export const ALLOWED_TRANSITIONS: Record<string, OrderStatus[]> = {
  CREATED: ['PROCESSING', 'PENDING_PAYMENT', 'CANCELLED'],
  PROCESSING: ['INVOICE_SENT', 'PENDING_PAYMENT', 'CANCELLED'],
  INVOICE_SENT: ['PENDING_PAYMENT', 'AWAITING_CONFIRMATION', 'CANCELLED'],
  PENDING_PAYMENT: ['PAID', 'PARTIALLY_PAID', 'PAYMENT_FAILED', 'CANCELLED'],
  PAYMENT_FAILED: ['PENDING_PAYMENT', 'CANCELLED'],
  AWAITING_CONFIRMATION: ['SHIPPED', 'CANCELLED'],
  PAID: ['SHIPPED', 'REFUNDED'],
  PARTIALLY_PAID: ['SHIPPED', 'PENDING_PAYMENT', 'CANCELLED'],
  SHIPPED: ['IN_TRANSIT', 'DELIVERED'],
  IN_TRANSIT: ['DELIVERED'],
  DELIVERED: ['PAID', 'PENDING_PAYMENT', 'COMPLETED'],
  CANCELLED: ['REFUNDED'],
  REFUNDED: ['COMPLETED'],
  COMPLETED: [],
};

export function getAllowedTransitions(currentStatus: string): OrderStatus[] {
  return ALLOWED_TRANSITIONS[currentStatus] ?? [];
}
